# Generated by Django 5.1.1 on 2024-12-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportResistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('pivot', models.FloatField(blank=True, null=True)),
                ('resistance_1', models.FloatField(blank=True, null=True)),
                ('support_1', models.FloatField(blank=True, null=True)),
                ('resistance_2', models.FloatField(blank=True, null=True)),
                ('support_2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Support and Resistance',
                'verbose_name_plural': 'Support and Resistance',
                'unique_together': {('datetime', 'symbol')},
            },
        ),
    ]
