# Generated by Django 5.1.1 on 2024-10-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transact_no', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer', models.CharField(blank=True, max_length=100, null=True)),
                ('seller', models.CharField(blank=True, max_length=100, null=True)),
                ('repeated_trades_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('price_manipulation_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('painting_the_tape_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('volume_spike_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('circular_trading_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('pump_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('dump_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('seller_reappears_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('suspicious', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
