# Generated by Django 5.1.1 on 2024-10-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manupulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoilerRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('seller', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('volume', models.CharField(blank=True, max_length=100, null=True)),
                ('boiler_room_flag', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
