# Generated by Django 5.1.1 on 2024-10-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manupulation', '0007_rampingdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdTuningData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer', models.CharField(blank=True, max_length=100, null=True)),
                ('seller', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('volume', models.CharField(blank=True, max_length=100, null=True)),
                ('high_value_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('low_value_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('frequent_buyer_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('rare_buyer_flag', models.BooleanField(blank=True, default=False, null=True)),
                ('potential_anomaly', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
