# Generated by Django 5.1.1 on 2024-12-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubIndices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indices', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('current', models.CharField(blank=True, max_length=100, null=True)),
                ('change', models.FloatField(blank=True, null=True)),
                ('percent_change', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
