# Generated by Django 5.1.1 on 2024-09-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RsiSummary',
        ),
    ]
