# Generated by Django 5.1.1 on 2024-09-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('summary', '0002_delete_rsisummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='RsiSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('positive', models.IntegerField(default=0)),
                ('negative', models.IntegerField(default=0)),
                ('neutral', models.IntegerField(default=0)),
            ],
        ),
    ]
