# Generated by Django 5.1.1 on 2024-10-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0004_rsisummary_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacdSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('positive', models.IntegerField(blank=True, default=0, null=True)),
                ('negative', models.IntegerField(blank=True, default=0, null=True)),
                ('neutral', models.IntegerField(blank=True, default=0, null=True)),
                ('time', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rsisummary',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rsisummary',
            name='negative',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rsisummary',
            name='neutral',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rsisummary',
            name='positive',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rsisummary',
            name='symbol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
