from django.urls import path
from . import views
urlpatterns=[
    path('rsi/',views.rsi_view,name='rsi'),
    path('macd/',views.macd_view,name='macd'),
    path('cci/',views.cci_view,name='cci'),
    path('ao/',views.ao_view,name='ao'),
    path('mom/', views.momentum_view, name='mom-api'),
    path('stochrsi/', views.stochrsi_view, name='stochrsi-api'),
    path('willr/', views.willr_view, name='willr-api'),
    path('uo/', views.uo_view, name='uo_view'),
    path('bop/',views.bop_view,name='bop'),
    path('vwma/',views.vwma_view,name='vwma'),
    path('adx/',views.adx_view,name='adx'),
    path('apo/',views.get_apo_data),
    path('bias/',views.get_bias_data),
    path('brar/',views.get_brar_data),
    path('cfo/',views.get_cfo_data),
    path('cg/',views.get_cg_data),
    path('cmo/',views.get_cmo_data),
    path('coppock/',views.get_coppock_data),
    path('cti/',views.get_cti_data),
    path('dm/',views.get_dm_data),
    path('er/',views.get_er_data),
    path('eri/',views.get_eri_data),
    path('fisher/',views.get_fisher_data),
    path('inertia/',views.get_inertia_data),
    path('kdj/',views.get_kdj_data),
    path('kst/',views.get_kst_data),
    path('pgo/',views.get_pgo_data),
    path('ppo/',views.get_ppo_data),
    path('psl/',views.get_psl_data),
    path('pvo/',views.get_pvo_data),
    path('qqe/',views.get_qqe_data),
    path('roc/',views.get_roc_data),
    path('rsx/',views.get_rsx_data),
    path('rvgi/',views.get_rvgi_data),
    path('stc/',views.get_stc_data),
    path('slope/',views.get_slope_data),
    path('smi/',views.get_smi_data),
    path('squeez/',views.get_squeez_data),
    path('squeez-pro/',views.get_squeez_pro_data),
    path('stoch/',views.get_stoch_data),
    path('trix/',views.get_trix_data),
    path('tsi/',views.get_tsi_data),

]
