# Generated by Django 5.1.1 on 2024-09-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0003_sma20model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sma20model',
            name='close_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
