# Generated by Django 5.1.1 on 2024-09-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0008_sma200model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sma5model',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sma5model',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
