# Generated by Django 5.1.1 on 2024-09-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0009_sma5model_date_sma5model_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sma5model',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sma5model',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
