# Generated by Django 5.1.1 on 2024-11-28 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0012_sma200model_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sma100model',
            name='close_price',
        ),
        migrations.RemoveField(
            model_name='sma10model',
            name='close_price',
        ),
        migrations.RemoveField(
            model_name='sma200model',
            name='close_price',
        ),
        migrations.RemoveField(
            model_name='sma20model',
            name='close_price',
        ),
        migrations.RemoveField(
            model_name='sma30model',
            name='close_price',
        ),
        migrations.RemoveField(
            model_name='sma50model',
            name='close_price',
        ),
        migrations.RemoveField(
            model_name='sma5model',
            name='close_price',
        ),
    ]
