# Generated by Django 5.1.1 on 2024-09-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pivotpoint',
            name='r1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pivotpoint',
            name='r2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pivotpoint',
            name='r3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pivotpoint',
            name='s1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pivotpoint',
            name='s2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pivotpoint',
            name='s3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
