# Generated by Django 5.1.1 on 2024-11-28 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pivot', '0005_camrillapivotpoint_date_camrillapivotpoint_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camrillapivotpoint',
            name='close',
        ),
        migrations.RemoveField(
            model_name='camrillapivotpoint',
            name='high',
        ),
        migrations.RemoveField(
            model_name='camrillapivotpoint',
            name='low',
        ),
        migrations.RemoveField(
            model_name='fibonaccipivotpoint',
            name='close',
        ),
        migrations.RemoveField(
            model_name='fibonaccipivotpoint',
            name='high',
        ),
        migrations.RemoveField(
            model_name='fibonaccipivotpoint',
            name='low',
        ),
        migrations.RemoveField(
            model_name='pivotpoint',
            name='close',
        ),
        migrations.RemoveField(
            model_name='pivotpoint',
            name='high',
        ),
        migrations.RemoveField(
            model_name='pivotpoint',
            name='low',
        ),
    ]
