# Generated by Django 5.1.1 on 2024-10-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorsheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorsheetdata',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
