# Generated by Django 5.1.1 on 2024-11-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorsheet', '0003_alter_floorsheetdata_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorsheetdata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
