# Generated by Django 5.1.1 on 2024-11-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorsheet', '0005_stocksummaryreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.IntegerField(blank=True, null=True)),
                ('stock_symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('total_quantity_bought', models.IntegerField(blank=True, null=True)),
                ('total_amount_spent', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
