# Generated by Django 5.1.1 on 2024-11-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorsheet', '0006_buyeractivityreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyeractivityreport',
            name='buyer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
