# Generated by Django 5.1.1 on 2024-11-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorsheet', '0007_alter_buyeractivityreport_buyer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('total_quantity_sold', models.FloatField(blank=True, null=True)),
                ('total_amount_received', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='buyeractivityreport',
            old_name='stock_symbol',
            new_name='symbol',
        ),
    ]
