# Generated by Django 5.1.1 on 2024-12-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorsheet', '0008_selleractivityreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksummaryreport',
            name='average_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocksummaryreport',
            name='total_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
