# Generated by Django 5.1.1 on 2024-12-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorsheet', '0009_stocksummaryreport_average_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyeractivityreport',
            name='avg_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyeractivityreport',
            name='max_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyeractivityreport',
            name='min_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
