# Generated by Django 5.1.1 on 2024-12-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorsheet', '0012_highvaluetransactionreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolatilityAnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('min_rate', models.FloatField(blank=True, null=True)),
                ('max_rate', models.FloatField(blank=True, null=True)),
                ('avg_rate', models.FloatField(blank=True, null=True)),
                ('stddev_rate', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
