# Generated by Django 5.1.1 on 2024-12-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorsheet', '0015_pricemovementanalysisreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricemovementanalysisreport',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
