# Generated by Django 5.1.1 on 2024-12-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorsheet', '0016_pricemovementanalysisreport_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidityConcentrationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('total_quantity_traded', models.IntegerField(blank=True, null=True)),
                ('lcr_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('liquidity_concentration', models.CharField(blank=True, max_length=100, null=True)),
                ('interpretation', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
