# Generated by Django 5.1.1 on 2024-12-01 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floorsheet', '0017_liquidityconcentrationreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liquidityconcentrationreport',
            old_name='stock_symbol',
            new_name='symbol',
        ),
    ]
