# Generated by Django 5.1.1 on 2024-12-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorsheet', '0018_rename_stock_symbol_liquidityconcentrationreport_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceVolatilityVolumeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('price_change_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('volume_change_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vvr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('market_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('interpretation', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
