# Generated by Django 5.1.1 on 2024-12-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorsheet', '0019_pricevolatilityvolumereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricevolatilityvolumereport',
            name='price_change_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricevolatilityvolumereport',
            name='volume_change_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricevolatilityvolumereport',
            name='vvr',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
