# Generated by Django 5.1.1 on 2024-12-01 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floorsheet', '0022_stockpricerangereport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockpricerangereport',
            old_name='stock_symbol',
            new_name='symbol',
        ),
    ]
