# Generated by Django 5.1.1 on 2024-12-03 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorsheet', '0024_brokervolumeconcentrationreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('symbols', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='floorsheetdata',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='floorsheet.sector'),
        ),
    ]
